### ISSUE TITLE
wrong error code ApplicationNotAuthenticated when auth service timeout

### ISSUE THREAD

**Issue by vincentfretin** [Azure/azure-spatial-anchors-samples#132]
With the BasicDemo from this repo on
- Android Samsung S8
- Unity 2019.2.20f1
- ASA SDK 2.1.1

The watcher can trigger the following error (catched in the CloudManager_Error method)
"Error: Application did not provide valid credentials and therefore could not authenticate" that is shown to the user in the feedbackBox. The message come from a CloudSpatialException exception with errorCode ApplicationNotAuthenticated.
The error is misleading, the credentials are perfectly valid here, I made it works 5 minutes before that. It's actually the service that timeout with the following error "nError: gRPC error code [3] - msg [Unable to obtain authentication token: {The token service encountered an error.}] - ReqCV [] - ResCV []".
I think the exception error code should really be in this case CannotConnectToServer.

example of stacktrace I saw from the logcat panel in android studio:
```
"Error: Application did not provide valid credentials and therefore could not authenticate"
ApplicationNotAuthenticated = 79
Assets/AzureSpatialAnchors.SDK/Plugins/Common/AzureSpatialAnchorsBridge.cs

2020-02-19 13:46:08.117 4612-4947/? E/HttpRequestClient: Failed to execute async request
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:584)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355) 
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227) 
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) 
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-02-19 13:46:08.119 4612-4811/? I/Unity: [SelectAndProcessNextAvailableMobileArFrame] Create or query sufficiency status hash changed (notificationMask: a). Notifying listeners now.
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.123 4612-4854/? I/Unity: [ShouldFireLocate] Will not locate because locate is already underway
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.125 4612-4854/? I/Unity: [HandleFeedbackUpdated] Progress for locate was made since last request: 1, fired another locate operation: false
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.127 4612-4859/? I/Unity: Unable to obtain authentication token: {The token service encountered an error.}
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.129 4612-4869/? I/Unity: ProcessPoseQueryStreamingEventsUntilCompletion - entry
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.131 4612-4869/? I/Unity: ResetPoseQueryProcessStreamAndAssociatedState()
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.132 4612-4869/? I/Unity: ProcessPoseQueryStreamingEvents - OnError: gRPC error code [3] - msg [Unable to obtain authentication token: {The token service encountered an error.}] - ReqCV [] - ResCV []
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.138 3208-3208/? I/keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
2020-02-19 13:46:08.141 4612-4869/? I/Unity: Discover was unauthenticated!
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 13:46:08.141 4612-4859/? I/Unity: ServerUnreachable: Could not establish Pose Query Processor Stream!
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

or 

```
2020-02-19 14:13:14.103 6850-7091/? E/HttpRequestClient: Failed to execute async request
    java.net.SocketTimeoutException: failed to connect to sts.mixedreality.azure.com/137.116.57.240 (port 443) from /192.168.1.11 (port 34404) after 10000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
        at libcore.io.IoBridge.connect(IoBridge.java:129)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-02-19 14:13:24.680 6850-7052/? I/Unity: Unable to obtain authentication token: {The token service encountered an error.}
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.685 6850-7056/? I/Unity: ProcessPoseQueryStreamingEventsUntilCompletion - entry
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.688 6850-7056/? I/Unity: ResetPoseQueryProcessStreamAndAssociatedState()
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.693 6850-7052/? I/Unity: ServerUnreachable: Could not establish Pose Query Processor Stream!
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.693 6850-7056/? I/Unity: ProcessPoseQueryStreamingEvents - OnError: gRPC error code [3] - msg [Unable to obtain authentication token: {The token service encountered an error.}] - ReqCV [] - ResCV []
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.695 6850-7056/? I/Unity: Discover was unauthenticated!
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.697 6850-7056/? I/Unity: ProcessPoseQueryStreamingEventsUntilCompletion - DiscoverComplete but IsDiscoverComplete returned failure 3.
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.700 6850-7073/? I/Unity: OnError - application did not provide valid credentials and therefore could not authenticate
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.703 3208-3208/? I/keymaster_tee: [INFO]:  (nwd_keymaster_mdfpp.cpp:791) entered get_key_characteristics function.
2020-02-19 14:13:24.707 6850-7073/? I/Unity: application did not provide valid credentials and therefore could not authenticate
    EPV.ASAManager:CloudManager_Error(Object, SessionErrorEventArgs)
    Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
    Microsoft.Azure.SpatialAnchors.SessionErrorDelegate:Invoke(Object, SessionErrorEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.712 6850-7073/? I/Unity: Watcher 1 fired another locate operation.
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.712 6850-7044/? I/Unity: RunDiscoverAsync - Running a Discover iteration with 1 DiscoverOptions
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.714 6850-7044/? I/Unity: RunDiscoverAsync - Creating new Pose Query Processor Stream
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-19 14:13:24.715 5163-7526/? D/ConnectivityService: filterNetworkStateForUid() uid: 10348, pid: 6850
2020-02-19 14:13:24.715 5163-7526/? D/ConnectivityService: isNetworkWithLinkPropertiesBlocked: uid=10348, vpn=DISCONNECTED,false
2020-02-19 14:13:24.716 5163-7526/? D/ConnectivityService: filterNetworkStateForUid() uid: 10348, pid: 6850, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
2020-02-19 14:13:24.716 6850-7044/? I/Unity: RunDiscoverAsync - Snapshot - Counts of Cached NeighborhoodAnchors: 0. Cached SpatialAnchors: 2.
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
```

**Comment by vincentfretin** [comment]
I add the same timeout issue at the same time on both Android (Samsung S8) and iOS (iPad 2018 6th gen).

**Comment by vincentfretin** [comment]
I see SDK 2.2.0 added a new HttpTimeout error code. I will assume this error code is used instead of ApplicationNotAuthenticated for the stacktraces I shown. I close the issue. I'll reopen if I get the issue again.

**Comment by vincentfretin** [comment]
With SDK 2.2.0, after trying to save new anchor, I got a CloudSpatialException with error code ServerError triggered by a json error after a service timeout I believe. So this is not using the new HttpTimeout.

```
2020-02-21 11:19:24.030 12217-12490/? E/HttpRequestClient: Failed to execute async request
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:584)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355) 
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227) 
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215) 
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-02-21 11:19:24.037 12217-12409/? I/Unity: N15SpatialServices47CreateNeighborhoodAnchorAndSpatialAnchorRequestE returned HTTP 0. ReqCV: ryEkiaccTxOvng26ML3ABw. RespCV: .
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-21 11:19:24.042 12217-12409/? I/Unity: CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0. ReqCV: ryEkiaccTxOvng26ML3ABw. ResCV: . JSON Error: 
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-02-21 11:19:24.044 12217-12485/? I/Unity: OnError - Service unavailable or unspecified error found
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
    Microsoft.Azure.SpatialAnchors.OnLogDebugDelegate:Invoke(Object, OnLogDebugEventArgs)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by RamonArguelles** [comment]
Hi @vincentfretin , thanks for reporting! I've filed an internal issue (#26120953) for this so that we can take a look at it.

**Comment by Varnauld** [comment]
Hello, 
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team. 
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our Feedback hub

Thank you
