### ISSUE TITLE
CreateAnchorAsync incorrectly throws a ServerError exception when no WiFi is available

### ISSUE THREAD

**Issue by sublimeRich** [Azure/azure-spatial-anchors-samples#146]
If WiFi is disabled when `CreateAnchorAsync` is called, a `CloudSpatialException` is thrown with an error code indicating `CloudSpatialErrorCode.ServerError'.

The documentation states '_Cloud Service returned an unspecified error_', which implies an error in the Cloud Service rather than the Cloud Service being unreachable.  I'm not sure if this is a documentation error or an incorrect return error code; returning `CannotConnectToServer` (or `HttpTimeout` if more appropriate) seems more intuitive.

Seen on Android, using both SDK 2.1.1 and 2.2.0

**Comment by RamonArguelles** [comment]
Hi @sublimeRich, thanks a lot for your feedback. I've filed an internal work item (#26122484) for this so that we can track it..

**Comment by grabowCommuter** [comment]
I get similar error, even if connected via WiFi:

2021-03-04 20:18:54.942 D/ASACloud: StoreAndWatcherTrackedState::TryCreateInternalAsync for a new SpatialAnchor.
2021-03-04 20:18:54.942 D/ASACloud: StoreAndWatcherTrackedState::TryCreateWithNewNeighborhoodAnchor
2021-03-04 20:18:54.942 D/ASACloud: [MobileNeighborhoodManager::TryGetPoseBetweenAnchors] Pose computed successfully.
2021-03-04 20:18:54.946 I/chatty: uid=10278(u0_a278) Thread-13 identical 23 lines
2021-03-04 20:18:54.947 D/ASACloud: [MobileNeighborhoodManager::TryGetPoseBetweenAnchors] Pose computed successfully.
2021-03-04 20:18:54.947 D/ASACloud: [MobileNeighborhoodManager::GetAnchorNeighborhoodDataAsync] Creating anchor blob using 24 key-frames.
2021-03-04 20:18:54.949 D/ASACloud: [MobileNeighborhoodManager::GetAnchorNeighborhoodDataAsync] Preparing blob for creation.  Client-Side Triangulation: Disabled
2021-03-04 20:18:54.970 D/ASACloud: [MobileNeighborhoodManager::GetAnchorNeighborhoodDataAsync] Anchor neighborhood data is available. Size: 473837.
2021-03-04 20:18:54.971 D/ASACloud: RestClient::CreateNeighborhoodAnchorAndSpatialAnchorAsync - ReqCV: A2LvfXqXRXGBk6zBabh4LA
2021-03-04 20:18:58.158 I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2021-03-04 20:19:02.842 E/ACameraMetadata: getConstEntry: cannot find metadata tag 65578
2021-03-04 20:19:05.398 E/HttpRequestClient: Failed to execute async request
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:232)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:42)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:92)
        at okhttp3.RequestBody$2.writeTo(RequestBody.java:98)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:826)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179) 
        at okio.RealBufferedSink.write(RealBufferedSink.java:42) 
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:295) 
        at okio.ForwardingSink.write(ForwardingSink.java:35) 
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149) 
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179) 
        at okio.RealBufferedSink.write(RealBufferedSink.java:92) 
        at okhttp3.RequestBody$2.writeTo(RequestBody.java:98) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2021-03-04 20:19:05.399 D/ASACloud: N15SpatialServices47CreateNeighborhoodAnchorAndSpatialAnchorRequestE returned HTTP 0. ReqCV: A2LvfXqXRXGBk6zBabh4LA. RespCV: .
2021-03-04 20:19:05.403 D/ASACloud: CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0. ReqCV: A2LvfXqXRXGBk6zBabh4LA. ResCV: . JSON Error: 
2021-03-04 20:19:05.404 D/ASACloud: OnError - Service unavailable or unspecified error found
2021-03-04 20:19:05.405 E/ASACloud: Service unavailable or unspecified error found

**Comment by msftradford** [comment]
@grabowCommuter, thanks for reaching out! If you don't mind, it would be great if you could file a new issue for this incident. Please also be aware that [ASA SDK 2.7.0 in currently the minimum version](https://github.com/Azure/azure-spatial-anchors-samples/issues/232) and if you use a version < 2.7.0, you will receive a similar error message.
