### ISSUE TITLE
HoloLens runtime issue

### ISSUE THREAD

**Issue by dtytgat** [Azure/azure-spatial-anchors-samples#21]
I'm trying to run the AzureSpatialAnchorsBasicDemo Unity scene on the HoloLens, however I seem to be getting some runtime issues. I've added a filtered version of the VS output below, only reflecting the potential error causes or the application state changes.

I'm using Unity 2018.3.13f1 and Visual Studio 17.

Would anyone here have a clue of the problem at hand?

```Unable to find method Internal_ScriptableRuntimeReflectionSystemWrapper_TickRealtimeProbes in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.ScriptableRuntimeReflectionSystemWrapper
(Filename: C:\buildslave\unity\build\Runtime/Scripting/CommonScriptingClasses.cpp Line: 143)
...
If your machine has multiple graphics adapters, Unity may have created a WindowContext on the wrong adapter. If you experience a black screen when playing, please restart the Editor. 
(Filename: C:\buildslave\unity\build\Runtime/VR/VRDevice.cpp Line: 319)
...
The referenced script on this Behaviour (Game Object 'First Person Camera') is missing!
The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
The referenced script on this Behaviour (Game Object 'ARCore Device') is missing!
The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
...
Azure Spatial Anchors Demo Script Start
Azure Spatial Anchors Demo script started
...
error:14090086:lib(20):func(144):reason(134)
error:14090086:lib(20):func(144):reason(134)
error:14090086:lib(20):func(144):reason(134)
error:14090086:lib(20):func(144):reason(134)
...
State from DemoStepCreateSession to DemoStepConfigSession
State from DemoStepConfigSession to DemoStepStartSession
...
AzureSpatialAnchors - Session Identifier: 8e...<anonymized>...c93 [AUTOMATION]
...
AzureSpatialAnchors - Configured AnchorServiceUrl: https://manage.sa.mixedreality.azure.com/
AzureSpatialAnchors - Configured AuthServiceUrl: https://sts.mixedreality.azure.com/
AzureSpatialAnchors - Configured AccountId: 32...<anonymized>...5c
AzureSpatialAnchors - Configured DeviceOsVersion: 10.0.17134.111
AzureSpatialAnchors - Configured SdkPackageType: 
AzureSpatialAnchors - Configured SdkVersion: 1.1.0
AzureSpatialAnchors - Configured ArPlatformVersion: 10.0.17134.111
AzureSpatialAnchors - Configured MiddlewareVersions: 
...
Exception thrown: 'System.InvalidOperationException' in Assembly-CSharp.dll
'HelloAR U3D.exe' (CoreCLR: CoreCLR_UWP_Domain): 
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll
InvalidOperationException: Unknown exception causing failure. Request CV: . Response CV: .
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.set_EnableProcessing(Boolean value)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsBasicDemoScript.AdvanceDemo()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<OnSelectInteraction>b__29_0()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.Update()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsBasicDemoScript.Update()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsBasicDemoScript.$Invoke18Update(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)
```

**Comment by vriveras** [comment]
@dtytgat , I noticed the the Windows build you are using is 10.0.17134.111 we need RS5 build 17720 as a minimum requirement for the SDK. Can you upgrade and give it a try again?

**Comment by Alberto-Vega-MSFT** [comment]
@dtytgat Were you able to resolve your issue?
