### ISSUE TITLE
Custom application crashes when creating a CloudSpatialAnchorSession object

### ISSUE THREAD

**Issue by Axel-P** [Azure/azure-spatial-anchors-samples#24]
Hi!

I've been playing with the android sample of the sample project and decided to build an app copying the code from the sample. However, the android device that runs the original sample keeps crashing on my custom project when trying to create a new `CloudSpatialAnchorSession` object.

The error looks like this:

> 2019-05-15 17:04:46.195 28901-28901/com.azurelib.azurecloudanchorstest E/loudanchorstes: No implementation found for com.microsoft.azure.spatialanchors.status com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_create(com.microsoft.azure.spatialanchors.Out) (tried Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1create and Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1create__Lcom_microsoft_azure_spatialanchors_Out_2)
2019-05-15 17:04:46.229 28901-28901/com.azurelib.azurecloudanchorstest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.azurelib.azurecloudanchorstest, PID: 28901
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:389)
        at android.view.View.performClick(View.java:6669)
        at android.view.View.performClickInternal(View.java:6638)
        at android.view.View.access$3100(View.java:789)
        at android.view.View$PerformClick.run(View.java:26145)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
        at android.view.View.performClick(View.java:6669) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for com.microsoft.azure.spatialanchors.status com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_create(com.microsoft.azure.spatialanchors.Out) (tried Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1create and Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1create__Lcom_microsoft_azure_spatialanchors_Out_2)
        at com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_create(Native Method)
        at com.microsoft.azure.spatialanchors.CloudSpatialAnchorSession.<init>(CloudSpatialAnchorSession.java:50)
        at com.azurelib.azurecloudanchorstest.AzureSpatialAnchorsManager.<init>(AzureSpatialAnchorsManager.java:39)
        at com.azurelib.azurecloudanchorstest.SharedActivity.createButtonClicked(SharedActivity.java:73)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384) 
        at android.view.View.performClick(View.java:6669) 
        at android.view.View.performClickInternal(View.java:6638) 
        at android.view.View.access$3100(View.java:789) 
        at android.view.View$PerformClick.run(View.java:26145) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-05-15 17:04:52.158 28901-28915/com.azurelib.azurecloudanchorstest E/loudanchorstes: No implementation found for com.microsoft.azure.spatialanchors.status com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_release(long) (tried Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1release and Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1release__J)
2019-05-15 17:04:52.158 28901-28915/com.azurelib.azurecloudanchorstest E/System: Uncaught exception thrown by finalizer
2019-05-15 17:04:52.169 28901-28915/com.azurelib.azurecloudanchorstest E/System: java.lang.UnsatisfiedLinkError: No implementation found for com.microsoft.azure.spatialanchors.status com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_release(long) (tried Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1release and Java_com_microsoft_azure_spatialanchors_NativeLibrary_ssc_1cloud_1spatial_1anchor_1session_1release__J)
        at com.microsoft.azure.spatialanchors.NativeLibrary.ssc_cloud_spatial_anchor_session_release(Native Method)
        at com.microsoft.azure.spatialanchors.CloudSpatialAnchorSession.finalize(CloudSpatialAnchorSession.java:62)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:256)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:243)
        at java.lang.Daemons$Daemon.run(Daemons.java:109)
        at java.lang.Thread.run(Thread.java:764)

The problem  seems to be that `com.microsoft.azure.spatialanchors.NativeLibrary` cannot be found. However, I've copied pretty much all settings from the sample. The Gradle scripts are the same. The manifest has the same permissions, features and meta-data. The android versions are pretty much the same. Both projects are running on the same device... I'm having a hard time figuring out why the sample can access all of the classes of the Azure library but my custom project can't access `NativeLibrary`.

The actual crash happens in the Azure library. When the constructor for `CloudSpatialAnchorSession` gets called, the second line of the constructor fails to find the proper implementation:
```
public CloudSpatialAnchorSession() {
    Out<Long> result_handle = new Out();
    status resultStatus = NativeLibrary.ssc_cloud_spatial_anchor_session_create(result_handle);
    this.handle = (Long)result_handle.value;
    NativeLibraryHelpers.checkStatus(this.handle, resultStatus);
    CookieTracker.add(this);
}
```
It lands in a dead-end:
```
class NativeLibrary {
    NativeLibrary() {
    }
    ...
    static native status ssc_cloud_spatial_anchor_session_create(Out<Long> var0);
    ...
}
```

**Comment by dotMorten** [comment]
I'm hitting the exact same thing with my Xamarin.Android bindings:
![image](https://user-images.githubusercontent.com/1378165/58573213-21c2e400-81f2-11e9-838a-a00b67060db9.png)
I've checked that both the JNI and NDK .so files are deployed (I probably only need the JNI one but just wanted to be sure :-) )

I've get my repo with reproducer set up here: https://github.com/dotMorten/Xamarin.AzureSpatialAnchors

I'm also noticing that if I call `Microsoft.CloudServices.Initialize(this);` I'm met with this concerning exception:
`Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/appcenter/analytics/Analytics;`
I don't seem to be able to find any indication that the appcenter analytics sdk is a requirement, and if it was, I'm seriously concerned about forcing analytics on users of an SDK, as we might unknowingly be missing a privacy policy, and we have no way to know what sort of information you're logging, but the responsibility is on us as the app developers.

**Comment by Axel-P** [comment]
> 
> 
> I'm hitting the exact same thing with my Xamarin.Android bindings:

Actually, my initial intent was to integrate this into a Xamarin project given that Microsoft says in their FAQ about this API that Xamarin _should_ be able to use Spatial Anchors. But after landing on this issue and trying to find out what the problem was I ended up in the same spot with a clean Java project. If this issue happens to be solved for Xamarin as well that would be fantastic. I'll upload my Java project when I have some time.


> I'm also noticing that if I call `Microsoft.CloudServices.Initialize(this);` I'm met with this concerning exception:
> `Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/appcenter/analytics/Analytics;`
> I don't seem to be able to find any indication that the appcenter analytics sdk is a requirement, and if it was, I'm seriously concerned about forcing analytics on users of an SDK, as we might unknowingly be missing a privacy policy, and we have no way to know what sort of information you're logging, but the responsibility is on us as the app developers.

Yeah, I noticed that places like [Maven repository](https://mvnrepository.com/artifact/com.microsoft.azure.spatialanchors/spatialanchors_java/1.1.1) do signal appcenter-analytics (and okHttp) as dependencies. Although, because I didn't see any impacts or documentation about it, I didn't pay too much attention to that

**Comment by Axel-P** [comment]
I ended up solving this issue. It turns out this is not a configuration issue. Rather, I just needed to initialize Azure Anchors by adding this line: `CloudServices.initialize(this);`.

While this solves my issues for the Java project, I still can't run it on a Xamarin project :/

**Comment by dotMorten** [comment]
@axel-p what issue are you having on Xamarin?

**Comment by Axel-P** [comment]
@dotMorten A couple. The AARs themselves don't do much for me. When I try creating a library project for them the object browser doesn't seem to be able to read the contents of the files

If I use JARs, usually, I can at least see the functions that I'm supposed to use and I manage to compile although I've been getting multiple errors of different classes not being found. I'll try to get a clean project up to share and see how far I can get before it crashes

**Comment by Axel-P** [comment]
@dotMorten Turns out, I couldn't get too far. It either complains of not finding the ndk.so for azure or (when I add a ndk file) crashes without any information. I might just use Unity instead

Anyways, [here's the link](https://github.com/Axel-P/AzureSpatialAnchorsTest)
