### ISSUE TITLE
CloudSpatialException - Trying to run the demo

### ISSUE THREAD

**Issue by FabienDesgranges** [Azure/azure-spatial-anchors-samples#43]
I am trying to run the demo as explained here: [https://docs.microsoft.com/en-gb/azure/spatial-anchors/quickstarts/get-started-unity-hololens](https://docs.microsoft.com/en-gb/azure/spatial-anchors/quickstarts/get-started-unity-hololens)

Basically, I just put my Azure IDs and run the demo as explained. I then create a local Anchor that seems to work fine. The issue comes after trying to send the local Anchor to the cloud. A big CloudSpatialException appears on my Hololens screen.
Here is a part of the log file:

```
service unavailable or unspecified error found
 
(Filename: C:\...\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

CloudSpatialException: 
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<>c__DisplayClass68_0.<CreateAnchorAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<CreateAnchorAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.<StoreAnchorInCloud>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<>c__DisplayClass33_0.<<SaveCurrentObjectAnchorToCloud>b__0>d.MoveNext() 
(Filename: <Unknown> Line: 0)

Failed to save anchor Microsoft.Azure.SpatialAnchors.CloudSpatialException
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<>c__DisplayClass68_0.<CreateAnchorAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<CreateAnchorAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.<StoreAnchorInCloud>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<>c__DisplayClass33_0.<<SaveCurrentObjectAnchorToCloud>b__0>d.MoveNext()
```

So I tried this tutorial: [https://docs.microsoft.com/en-gb/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app](https://docs.microsoft.com/en-gb/azure/spatial-anchors/tutorials/tutorial-new-unity-hololens-app)
And it seems to have the same error: ASA Error: service unavailable or unspecified error found

I'm running on Windows 10, Visual Studio 2019. I've downloaded all requirements as explained in the "Prerequisites" section.
What should I do ?

**Comment by darax** [comment]
that's the first point in the demo where the access tokens are used.  Is it possible that the values for Spatial Anchors Account Id and Spatial Anchors Account Key and id are switched around?

**Comment by FabienDesgranges** [comment]
I've checked and they are not. I've deployed the exactly same unity app on an Android device, and it worked ! I was able to create and save a spatial anchor to the cloud. Still not able to do it using the hololens, so the problem is still here..

**Comment by darax** [comment]
what OS build is on your HoloLens?  Is there any debug output from before the exception?

**Comment by FabienDesgranges** [comment]
On the Hololens, I have the Windows 10 version 1809 for x86-based Holographic Devices.
Here is the whole log file

`Loading native plugins
  Loading AudioPluginMsHRTF.dll
Module information:
 Built with Compiler Ver '191326128'
 Built from '2018.3/release' branch
 Version is '2018.3.12f1 ...'
 Release build
 Application type 'D3D'
 OS 'Windows 10 (10.0.17763)'
PlayerConnection initialized from C:/.../Data (debug = 0)
[...]
Started listening to [0.0.0.0:55011]
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: HoloLens Graphics (ID=0x22b0)
    Vendor:   (null)
    VRAM:     604 MB
Initialize engine version: 2018.3.12f1
Unable to find method Internal_ScriptableRuntimeReflectionSystemWrapper_TickRealtimeProbes in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.ScriptableRuntimeReflectionSystemWrapper
 
(Filename: C:.../CommonScriptingClasses.cpp Line: 143)

If your machine has multiple graphics adapters, Unity may have created a WindowContext on the wrong adapter. If you experience a black screen when playing, please restart the Editor.
 
(Filename: C:\.../VRDevice.cpp Line: 319)

Created eye textures with a "separate" layout.  The "multi-pass" stereo mode will be used.

 
(Filename: C:\.../VRDevice.cpp Line: 2264)

Windows Mixed Reality spatial locatability state changed to Active.
 
(Filename: C:\..../HoloLensWorldManager.cpp Line: 315)

WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
UnloadTime: 4.123800 ms
AzureSpatialAnchorsDemoLauncher
 
(Filename: C:\.../Debug.bindings.h Line: 45)

The referenced script on this Behaviour (Game Object 'First Person Camera') is missing!
 
(Filename: C:\.../ManagedMonoBehaviourRef.cpp Line: 294)

The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
 
(Filename: C:\.../ManagedMonoBehaviourRef.cpp Line: 294)

The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
 
(Filename: C:\.../ManagedMonoBehaviourRef.cpp Line: 294)

The referenced script on this Behaviour (Game Object 'ARCore Device') is missing!
 
(Filename: C:\.../ManagedMonoBehaviourRef.cpp Line: 294)

The referenced script on this Behaviour (Game Object 'ARKitCamera') is missing!
 
(Filename: C:\.../ManagedMonoBehaviourRef.cpp Line: 294)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 59.703600 ms
Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 7 unused Assets to reduce memory usage. Loaded Objects now: 460. Operation took 25.988100 ms.
System memory in use: 21.1 MB.
>>Azure Spatial Anchors Demo Script Start
 
(Filename: C:\.../Debug.bindings.h Line: 45)

2
 
(Filename: C:\.../Debug.bindings.h Line: 45)

Azure Spatial Anchors Demo script started
 
(Filename: C:\.../Debug.bindings.h Line: 45)

State from DemoStepCreateSession to DemoStepConfigSession
 
(Filename: C:\.../Debug.bindings.h Line: 45)

State from DemoStepConfigSession to DemoStepStartSession
 
(Filename: C:\.../Debug.bindings.h Line: 45)

Processing True
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Session Identifier: [...]
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured AnchorServiceUrl: https://manage.sa.mixedreality.azure.com/
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured AuthServiceUrl: https://sts.mixedreality.azure.com/
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured AccountId: [...]
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured DeviceOsVersion: 10.0.17763.557
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured SdkPackageType: 
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured SdkVersion: 1.1.1
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured ArPlatformVersion: 10.0.17763.557
 
(Filename: C:\.../Debug.bindings.h Line: 45)

AzureSpatialAnchors - Configured MiddlewareVersions: 
 
(Filename: C:\.../Export/Debug.bindings.h Line: 45)

State from DemoStepStartSession to DemoStepCreateLocalAnchor
 
(Filename: C:\.../Debug.bindings.h Line: 45)

State from DemoStepCreateLocalAnchor to DemoStepSaveCloudAnchor
 
(Filename: C:\.../Debug.bindings.h Line: 45)

State from DemoStepSaveCloudAnchor to DemoStepSavingCloudAnchor
 
(Filename: C:\.../Debug.bindings.h Line: 45)

StoreAndWatcherTrackedState::TryCreateInternalAsync for a new SpatialAnchor.
 
(Filename: C:\.../Debug.bindings.h Line: 45)

StoreAndWatcherTrackedState::TryCreateWithNewNeighborhoodAnchor
 
(Filename: C:\.../Debug.bindings.h Line: 45)

GetNeighborhoodDataAsync -spatialAnchorQueryRoot == spatialAnchorLocationOrigin, skipping blob modification
 
(Filename: C:\.../Debug.bindings.h Line: 45)

RestClient::CreateNeighborhoodAnchorAndSpatialAnchorAsync - ReqCV: a9HznnYkRneGVK3YadJBsw
 
(Filename: C:\.../Debug.bindings.h Line: 45)

RestClient::GetAccessTokenAsync - ReqCV: iaHxJiTBQrKMaul8dFpfOg
 
(Filename: C:\.../Debug.bindings.h Line: 45)

struct SpatialServices::GetAccessTokenRequest returned HTTP 200. ReqCV: iaHxJiTBQrKMaul8dFpfOg. RespCV: FymFfSr9zUa/xAqXIWUFZw.0.
 
(Filename: C:\.../Debug.bindings.h Line: 45)

struct SpatialServices::CreateNeighborhoodAnchorAndSpatialAnchorRequest returned HTTP 0. ReqCV: a9HznnYkRneGVK3YadJBsw. RespCV: .
 
(Filename: C:\.../Debug.bindings.h Line: 45)

RestClient::CreateNeighborhoodAnchorAndSpatialAnchorAsync - Exception 'HRESULT: 80004005 Platform error code: 800c0008'
 
(Filename: C:\.../Debug.bindings.h Line: 45)

CreateNeighborhoodAnchorAndSpatialAnchor failed with HTTP error 0. ReqCV: a9HznnYkRneGVK3YadJBsw. ResCV: . JSON Error: .
 
(Filename: C:\.../Debug.bindings.h Line: 45)

OnError - service unavailable or unspecified error found
 
(Filename: C:\.../Debug.bindings.h Line: 45)

service unavailable or unspecified error found
 
(Filename: C:\.../Debug.bindings.h Line: 45)

CloudSpatialException: 
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<>c__DisplayClass68_0.<CreateAnchorAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<CreateAnchorAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.<StoreAnchorInCloud>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<>c__DisplayClass33_0.<<SaveCurrentObjectAnchorToCloud>b__0>d.MoveNext() 
(Filename: <Unknown> Line: 0)

Failed to save anchor Microsoft.Azure.SpatialAnchors.CloudSpatialException
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<>c__DisplayClass68_0.<CreateAnchorAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<CreateAnchorAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.<StoreAnchorInCloud>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<>c__DisplayClass33_0.<<SaveCurrentObjectAnchorToCloud>b__0>d.MoveNext()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Microsoft.Azure.SpatialAnchors.CloudSpatialException
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<>c__DisplayClass68_0.<CreateAnchorAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession.<CreateAnchorAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.<StoreAnchorInCloud>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<>c__DisplayClass33_0.<<SaveCurrentObjectAnchorToCloud>b__0>d.MoveNext()
 
(Filename: C:\.../Debug.bindings.h Line: 45)

Trimming D3D resources.
`

**Comment by darax** [comment]
thanks for the full log.  I am able to see the authentication request in our telemetry. That succeeded. The request to create an anchor I don't see in our telemetry.  This indicates that the request never actually made it to our servers.  The error code 800c0008 maps to INET_E_DOWNLOAD_FAILURE. A couple of ideas:
1. Try a different Wi-Fi network.  Clearly the one you are on *is* working, or the authentication request would fail.
2. The log you've posted appears to be from a couple of weeks ago.  Maybe try again and post a newer log?  What I mostly need are the ReqCV and ResCV values.
3. Check to make sure that we can get the spatial data from your HoloLens, paste this into the start function of AzureSpatialAnchorsDemoWrapper:
 // Ensure that the device is running a supported build with the spatialperception capability declared.
            bool accessGranted = false;
            try
            {
                Windows.Perception.Spatial.SpatialPerceptionAccessStatus accessStatus = await Windows.Perception.Spatial.SpatialAnchorExporter.RequestAccessAsync();
                accessGranted = (accessStatus == Windows.Perception.Spatial.SpatialPerceptionAccessStatus.Allowed);
            }
            catch { }

            if (!accessGranted)
            {
               Debug.Log("Unable to get access to spatial perception data");
            }

My HoloLens doesn't have the latest update (like you do), so I'm updating to see if there is an issue with the build.  The build happens to include updated firmware for the wifi adapter.

**Comment by FabienDesgranges** [comment]
Ok I've just found out the problem ! I was logged on my Hololens with a restricted account that prevented me from saving anchors to the cloud. Thanks for your help !

**Comment by RoyceThomasIype** [comment]
I also got this same issue when I tried to run on Android. I was able to solve the problem when I manually granted all the app permissions.
Hope this helps someone.

**Comment by tomCarnevale** [comment]
> I also got this same issue when I tried to run on Android. I was able to solve the problem when I manually granted all the app permissions.
> Hope this helps someone.

This was my issue, storage permissions had been denied but was never properly requested. Recommend that permissions are requested before attempting to save to cloud

**Comment by rptshri** [comment]
@RoyceThomasIype  I experienced the same error, tried manually giving permissions, but find;t work for me. Is it related to location of the server in any way? I am writing from India!_
