### ISSUE TITLE
HoloLens exception when connecting to Azure

### ISSUE THREAD

**Issue by me-Stoffel** [Azure/azure-spatial-anchors-samples#8]
Hey,

I got the basic and shared examples up and running on iOS and Android using Unity, as well as the web app published, without any problems. I can also build to HoloLens (also with Unity) and it starts up fine. However whenever I try to connect to Azure it seems not to succesfully get an access token back (also debug log "AzureSpatialAnchors - Configured AuthenticationToken: " states it as empty). I get the following exception:

`InvalidOperationException: Unknown exception causing failure. Request CV: . Response CV: .
   at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus(IntPtr handle, status value)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsDemoWrapper.set_EnableProcessing(Boolean value)
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsSharedAnchorDemoScript.AdvanceCreateFlowDemo()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsSharedAnchorDemoScript.AdvanceDemo()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.<OnSelectInteraction>b__27_0()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.DemoScriptBase.Update()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsSharedAnchorDemoScript.Update()
   at Microsoft.Azure.SpatialAnchors.Unity.Samples.AzureSpatialAnchorsSharedAnchorDemoScript.$Invoke23(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) `

I use the same azure resource Id, key (and for the shared example same url) as in the iOS and Android builds, where they work without issues. Any ideas what could be causing this? The Hololens is connected and can access the web app url fine via Edge. Neither basic scene nor shared one work, after the exception I can still continue to place the cube, but I don't think it saves it to azure in any ways. It then gets stuck at "Move your device to capture  more environment data: 0%".

**Comment by vriveras** [comment]
@me-Stoffel , If your are running any of the samples you will need to follow the section for configuring the AccountId and AccountKey to get the AuthToken properly.

The AuthToken is automatically gathered for you after you configure the AccountId and AccountKey in the SessionConfiguration object in the API. There is no need to configure a custom token service or application unless you have a specific scenario for it.

Unity [configuration ](https://docs.microsoft.com/en-us/azure/spatial-anchors/quickstarts/get-started-unity-android#configure-account-identifier-and-key) in the scene

Please let me know if you still are not able to get the API working after following the configuration sections.

**Comment by dtytgat** [comment]
@vriveras I'm running into the same problem and, as far as I know, I have configured the account id and key as required. I'm also getting the following message before the error of @me-Stoffel is thrown:

`Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.ni.dll` 

I'm not sure if these are related though...

**Comment by Alberto-Vega-MSFT** [comment]
@me-Stoffel any updates? were you able to resolve your issue?

**Comment by vriveras** [comment]
Closing issue no response
